### ISSUE TITLE
Feature Request: Templated Kernel and Bodies

### ISSUE THREAD

**Issue by pizzooid** [exafmm/exafmm-beta#22]
Hi, i think it would be nice to have:
- templated kernel classes, what i mean by that is that the kernel type gets passed to every class using the kernel functions and instead of declaring the multipole order and the kernel type in the makefile.am different kernels could be used at runtime, which would make it much easier to share it with other libraries and compile multiple kernels into one executable
- templated Source/Body, this would allow Kernels with different kinds of sources, in combiniation with the other feature Body and Source type could be referenced by the kernel class

Rio, would you be interested in anything of the sort? I could also help with the implementation.

Regards
Pietro

**Comment by rioyokota** [comment]
The old version had the kernels templates, but I removed this feature because I didn't have any demand for multiple kernels from one application, and it was increasing the compile time significantly. If you can find a way to do this without increasing the compile time, you can add this feature back and submit a pull request. Same for the templated source/body.

**Comment by pizzooid** [comment]
#23 should enable the first point, i did not see longer compile times
